### PR TITLE
Update on readme and remove requirements.txt

### PR DESCRIPTION
**Pull request by mdsatria**

### CODE REVIEW

**Comment by rudyhendrawn** [comment]
@mdsatria 
Why do we use yaml for the requirement file?

I think I can't remove it because I need it to deploy in the streamlit platform.

**Review by rudyhendrawn — COMMENTED** [review]
The conda environment is independent to the deployed app on any cloud platform, I thought if you want to deploy it locally you should use the same as the repository name.

**Comment by mdsatria** [comment]
> @mdsatria Why do we use yaml for the requirement file?
> 
> I think I can't remove it because I need it to deploy in the streamlit platform.

Because with yaml, we can create a new environment with a specific python version aside installed the required packages. Hence, it minimizes user effort in the installation process.
Regarding the streamlit, I cannot say much about yaml as I have little experience on streamlit. But, I looked at the streamlit documentation https://docs.streamlit.io/streamlit-cloud/get-started/deploy-an-app/app-dependencies , and it stated the yaml file is supported.

**Comment by mdsatria** [comment]
> The conda environment is independent to the deployed app on any cloud platform, I thought if you want to deploy it locally you should use the same as the repository name.

I do not quite understand what you want to say here. But, if you want the user can use a different environment name than the defined name in yaml file, the command to create environment from yml file should be
> conda create env -n environment_name -f environment.yml

**Comment by rudyhendrawn** [comment]
> > @mdsatria Why do we use yaml for the requirement file?
> > I think I can't remove it because I need it to deploy in the streamlit platform.
> 
> Because with yaml, we can create a new environment with a specific python version aside installed the required packages. Hence, it minimizes user effort in the installation process. Regarding the streamlit, I cannot say much about yaml as I have little experience on streamlit. But, I looked at the streamlit documentation https://docs.streamlit.io/streamlit-cloud/get-started/deploy-an-app/app-dependencies , and it stated the yaml file is supported.

**Pull request merged**
